<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>$(ProjectApplicationBaseName)</RootNamespace>
		<AssemblyName>$(ProjectApplicationBaseName)</AssemblyName>
		<OutputType>Exe</OutputType>
		<DefineConstants>$(DefineConstants);ASM15_2;DEFINE_MODEL_INCLUDE</DefineConstants>
		<ApplicationManifest>$(SolutionDir)src/apps/App/Assets/app.manifest</ApplicationManifest>
		<IsUiProject>true</IsUiProject>
		<ProjectName>ASM15-2</ProjectName>
	</PropertyGroup>
	<Import Project="$(SolutionDir)build/define/DefApp.csproj"/>
</Project>
