<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <RootNamespace>SourceGenerators1.Sample</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="DDD.UbiquitousLanguageRegistry.txt"/>
        <AdditionalFiles Include="DDD.UbiquitousLanguageRegistry.txt"/>
    </ItemGroup>

</Project>
