<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <RootNamespace>SG_pointcsv.Sample</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\SG_pointcsv\SG_pointcsv.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
    </ItemGroup>

    <ItemGroup>
        <None Remove="DDD.UbiquitousLanguageRegistry.txt"/>
        <AdditionalFiles Include="DDD.UbiquitousLanguageRegistry.txt"/>
    </ItemGroup>

</Project>
