namespace ZitApp.Models;

public enum WorkStep
{
	COMPLETED,
	SCAN_KEY_PART_CODE_DOING,
	SCAN_KEY_PART_CODE_COMPLETED,
	SCAN_SN_CODE_DOING,
	SCAN_SN_CODE_COMPLETED,
	MES_QUERY_DOING,
	MES_QUERY_COMPLETED,
	RECIPE_CHECK,
	RECIPE_SEND,
	RECIPE_WAIT,
	MES_IN_STATION_DOING,
	MES_IN_STATION_COMPLETED,
	MES_OUT_STATION_WAITING,
	MES_OUT_STATION_DOING,
	MES_OUT_STATION_COMPLETED,
}